; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform 		= espressif32
board 			= esp32doit-devkit-v1 
framework 		= arduino
monitor_speed 	= 115200
upload_port 	= Tap-o-meter_12.local
; upload_port 	= /dev/cu.wchusbserial58B90423431
; monitor_port 	= /dev/cu.SLAB_USBtoUART
lib_compat_mode = strict
monitor_eol     = CRLF  
monitor_echo    = yes  
monitor_filters = 
	; send_on_enter
	esp32_exception_decoder
lib_deps =
        knolleary/PubSubClient@2.8
        bblanchon/ArduinoJson@6.20.0
        mathieucarbou/MycilaWebSerial@^7.0.1

;; YOU SHOUD FUCKIN FIX THE ID SOME TIMES ITS THE MAC ADDRESS AND ANOTHER THE CHIPID

